# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  firebase-deploy:
    runs-on : ubuntu-latest
    
    steps :
      - uses : actions/checkout@master
      - uses : action/setup-node@master
        with : 
          node-version : '12.x'
      - run : npm install
      - run : npm run build
      - uses : w9jds/firebase-action@master
        with : 
          args : deploy --only hosting
        env : 
          FIREBASE_TOKEN : ${{secrets.FIREBASE_TOKEN}}
      
  
